name: A Blog
author: flowaflow
url: https://dade68.github.io
baseurl: 
resume_site: https://dade68.github.io
description: Welcome to my secrete park
github_username: dade68 
github: https://github.com/dade68
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : dade68.github.io
    owner : flowaflow
    admin : flowaflow
